class excepexample
{
 public static void main (String args[])
  {
   try 
  {
      int a[]= new int[7];
	a[4]= 30/2;
	System.out.println ("No Exception");
   }
	catch(ArrayIndexOutOfBoundsException e)
	{
	System.out.println("Array Exception ");
	}
	catch ( ArithmeticException e)
	{
	System.out.println("Arithmetic Exception");
	}
	catch (Exception e)
	{
	System.out.println("Common Exception ");
	}
	System.out.println("Out of Try catch");
	}
}



